services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/messenger
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      migration:
        condition: service_completed_successfully

  migration:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/messenger
    depends_on:
      postgres:
        condition: service_healthy
    # entrypoint: ["/bin/bash", "-c", "poetry install --with migration && poetry run alembic upgrade head"]
    entrypoint: ["/bin/bash", "-c", "/app/scripts/migration.sh"]

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messenger
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --databases 32
    environment:
      REDIS_PORT: 6379
      REDIS_REPLICATION_MODE: master
    restart: always
    ports:
      - "6379:6379"