"""Chat created at

Revision ID: 74912be129d5
Revises: 4b6026185951
Create Date: 2025-05-19 01:00:57.646963

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74912be129d5"
down_revision = "4b6026185951"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "chats", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "updated_at")
    op.drop_column("chats", "created_at")
    # ### end Alembic commands ###
